### PR TITLE
Fix date parsing with european date format (dd.mm.yyyy), fixes #8

### LINKED ISSUE #8: Date-Format Problem since ```forceParse``` update
Hi

Since the latest release, the datepicker has a sketchy behaviour. The problem appears only with European date format ('dd.mm.yyy').

When I click on (or enter manually) a date (e.g. "05.12.2015"),  the month and day switch on focus-out => "12.05.2015").
Using different formats, the problem could not be observed.

See this test:
```javascript
test('change input value', function(assert) {

  // normal date
  this.set('testDate','' );
  this.render(hbs`{{bootstrap-datepicker value=testDate format="dd.mm.yyyy" }}`);
  this.$('input').val('05.12.2015').trigger('focusout');
  assert.equal(this.get('testDate'), new Date('2015-12-05T00:00:00+0000'), 'converted javascript date');
  assert.equal(this.$('input').val(), '05.12.2015', 'typed date should stay');
});
```

outputs this:
image

any ideas? could this come from not checking format for converting?:
https://github.com/topaxi/ember-bootstrap-datepicker/blob/196190662f5dccc9c1ac0f96a49fa298f6ceaad8/addon/components/bootstrap-datepicker.js#L51

### PR DESCRIPTION
**Pull request by chvonrohr**

### CODE REVIEW

**Comment by topaxi** [comment]
Nice thanks! Tests are failing though, not sure if they were already failing before, I'll look into this as soon as I got some spare time.

**Comment by chvonrohr** [comment]
Hey, seems that I have missed your reply on the PR ;)
thanks for merging now. Unfortunately, I'm still fixing some minor issues as changes make use of new module API, which is not working with Ember 2.8 and 2.12 ...

I'm going to add fixes to this PR which will solve issues for those versions.

**Comment by chvonrohr** [comment]
I added 1 commit, for backporting to older ember versions. Although, this did not fix the problem with 2.8. I think this bug was already existing before my changes.

**Comment by topaxi** [comment]
Yes there were already problems in older Ember versions 👍 Thanks!

**Pull request merged**
